# Generated by Django 6.0.5 on 2026-06-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_name', models.CharField(max_length=255)),
                ('guide_type', models.CharField(choices=[('Guide', 'Guide'), ('Co-Guide', 'Co-Guide')], max_length=20)),
                ('registration_date', models.DateField()),
                ('awarded_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('awarded', 'Awarded')], default='ongoing', max_length=20)),
                ('points', models.FloatField(default=0)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_guidance', to='accounts.user')),
            ],
        ),
    ]
