# Generated by Django 6.0.5 on 2026-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEARNING_MATERIAL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcontribution',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
