# Generated by Django 6.0.5 on 2026-06-12 11:40

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('patent_number', models.CharField(max_length=100, unique=True)),
                ('patent_type', models.CharField(choices=[('GRANTED_FIRST', 'Granted Patent (1st Applicant)'), ('GRANTED_OTHER', 'Granted Patent (Other than 1st Applicant)'), ('PUBLISHED_FIRST', 'Patent Published (1st Applicant)'), ('PUBLISHED_OTHER', 'Patent Published (Other than 1st Applicant)')], max_length=30)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('certificate_file', models.FileField(blank=True, null=True, storage=core.storage.Patent_certificate(), upload_to='')),
                ('points', models.IntegerField(default=0)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_activities', to='accounts.user')),
            ],
        ),
    ]
