# Generated by Django 6.0.5 on 2026-06-14 08:11

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(max_length=255)),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_type', models.CharField(choices=[('SCI', 'SCI'), ('SCOPUS', 'Scopus'), ('UGC', 'UGC'), ('PEER_REVIEWED', 'Peer Reviewed')], max_length=20)),
                ('author_type', models.CharField(choices=[('FIRST_AUTHOR', '1st Author'), ('OTHER_AUTHOR', 'Other Than 1st Author')], max_length=20)),
                ('doi_number', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, storage=core.storage.JournalPublicationStorage(), upload_to='')),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_publications', to='accounts.user')),
            ],
        ),
    ]
