# Generated by Django 6.0.5 on 2026-06-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=500)),
                ('funding_agency', models.CharField(max_length=255)),
                ('grant_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grant_category', models.CharField(choices=[('gt_10', 'More than 10 Lakhs'), ('5_10', '5 to 10 Lakhs'), ('lt_5', 'Less than 5 Lakhs')], max_length=20)),
                ('investigator_role', models.CharField(choices=[('pi', 'Principal Investigator (PI)'), ('co_pi', 'Co-Principal Investigator (Co-PI)')], max_length=10)),
                ('sanction_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funded_projects', to='accounts.user')),
            ],
        ),
    ]
