# Generated by Django 6.0.5 on 2026-06-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedbackPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=255)),
                ('cycle_1_feedback', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory')], max_length=20, null=True)),
                ('cycle_2_feedback', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory')], max_length=20, null=True)),
                ('exam_result', models.CharField(blank=True, choices=[('ge_90', '>=90%'), ('ge_80', '>=80%'), ('ge_70', '>=70%'), ('lt_70', '<70%')], max_length=10, null=True)),
                ('points', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback_performances', to='accounts.user')),
            ],
        ),
    ]
