# Generated by Django 6.0.5 on 2026-06-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THEORY_COURSES_HANDLED', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedbackperformance',
            name='cycle_1_feedback',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfeedbackperformance',
            name='cycle_2_feedback',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory')], default='', max_length=20),
        ),
    ]
