# Generated by Django 6.0.5 on 2026-06-26 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THEORY_COURSES_HANDLED', '0002_alter_studentfeedbackperformance_cycle_1_feedback_and_more'),
        ('accounts', '0005_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedbackperformance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feedback_entries', to='accounts.user'),
        ),
    ]
