# Generated by Django 6.0.5 on 2026-06-13 07:15

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('CHAIRING_SESSION', 'Chairing Session'), ('INVITED_TALK', 'Invited Talk'), ('GUEST_LECTURE', 'Guest Lecture'), ('KEYNOTE_SPEECH', 'Keynote Speech')], max_length=30)),
                ('organization', models.CharField(max_length=255)),
                ('event_level', models.CharField(choices=[('INTERNATIONAL', 'International'), ('NATIONAL', 'National'), ('IIT_NIT', 'National IIT/NIT Level'), ('UNIVERSITY', 'University Level'), ('COLLEGE', 'College Level')], max_length=20)),
                ('event_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, storage=core.storage.Sessioncertificate(), upload_to='')),
                ('points', models.IntegerField(default=0)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairing_sessions', to='accounts.user')),
            ],
        ),
    ]
