# Generated by Django 6.0.5 on 2026-06-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERTIFICATE_COURSES_DONE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
