# Generated by Django 6.0.5 on 2026-06-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CERTIFICATE_COURSES_DONE', '0002_course_message'),
        ('accounts', '0004_alter_user_email_alter_user_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursedone', to='accounts.user'),
        ),
    ]
