# Generated by Django 6.0.5 on 2026-06-13 11:53

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('publication_type', models.CharField(choices=[('PROCEEDING', 'Conference Proceeding'), ('BOOK_CHAPTER', 'Book Chapter')], max_length=20)),
                ('indexing_type', models.CharField(choices=[('IEEE_SPRINGER_ELSEVIER', 'IEEE/Springer/Elsevier or Equivalent'), ('SCOPUS', 'Other Scopus Indexed')], max_length=30)),
                ('author_type', models.CharField(choices=[('FIRST_AUTHOR', 'First Author'), ('CO_AUTHOR', 'Other than First Author')], max_length=20)),
                ('publisher_name', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, storage=core.storage.ConferenceCertificate(), upload_to='')),
                ('points', models.IntegerField(default=0)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='accounts.user')),
            ],
        ),
    ]
