# Generated by Django 6.0.5 on 2026-06-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('register_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('dean', 'Dean'), ('hod', 'HOD'), ('committee_coordinator', 'Committee Coordinator'), ('department_incharge', 'Department Incharge'), ('faculty', 'Faculty')], max_length=50)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
