# Generated by Django 6.0.5 on 2026-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
