# Generated by Django 6.0.5 on 2026-06-20 18:11

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, storage=core.storage.Profile_image(), upload_to='')),
                ('headline', models.CharField(blank=True, help_text='e.g., Assistant Professor at XYZ College', max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.user')),
            ],
        ),
    ]
