# Generated by Django 6.0.5 on 2026-06-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_register_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_no',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
