# Generated by Django 6.0.5 on 2026-06-13 13:36

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDPs_Attended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FDP', 'FDP/Workshop'), ('CONFERENCE', 'Conference/Seminar')], max_length=20)),
                ('institute', models.CharField(choices=[('IIT', 'IIT'), ('NIT', 'NIT'), ('UNIVERSITY', 'University'), ('COLLEGE', 'College'), ('ABROAD', 'Abroad')], max_length=20)),
                ('duration', models.CharField(blank=True, choices=[('GE_2W', '>= 2 Weeks'), ('BW_1W_2W', '1 Week to 2 Weeks'), ('LT_1W', '< 1 Week')], max_length=20, null=True)),
                ('level', models.CharField(blank=True, choices=[('INTERNATIONAL', 'International'), ('NATIONAL', 'National')], max_length=20, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('certificate_file', models.FileField(blank=True, null=True, storage=core.storage.FDPs_Attended_Storage(), upload_to='')),
                ('points', models.IntegerField(default=0)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdp_activities', to='accounts.user')),
            ],
        ),
    ]
