# Generated by Django 6.0.5 on 2026-06-14 15:27

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=500)),
                ('publisher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher_type', models.CharField(choices=[('international', 'International Publisher'), ('national', 'National Publisher')], max_length=20)),
                ('isbn_status', models.CharField(choices=[('yes', 'ISBN Available'), ('no', 'ISBN Not Available')], max_length=10)),
                ('isbn_number', models.CharField(blank=True, max_length=100, null=True)),
                ('author_type', models.CharField(choices=[('first_author', '1st Author'), ('co_author', 'Other than 1st Author')], max_length=20)),
                ('publication_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, storage=core.storage.Book_publication_Storage(), upload_to='')),
                ('points', models.FloatField(blank=True, default=0, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_publications', to='accounts.user')),
            ],
        ),
    ]
