# Generated by Django 6.0.5 on 2026-06-12 10:26

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('membership_type', models.CharField(choices=[('INTERNATIONAL', 'International Membership'), ('NATIONAL', 'National Membership')], max_length=20)),
                ('membership_id', models.CharField(blank=True, max_length=100, null=True)),
                ('points', models.IntegerField(default=0)),
                ('membership_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, storage=core.storage.MembershipStorage(), upload_to='')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_memberships', to='accounts.user')),
            ],
        ),
    ]
