# Generated by Django 6.0.5 on 2026-06-14 07:11

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProjectWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('BTECH', 'B.Tech Project'), ('MTECH', 'M.Tech Project')], max_length=20)),
                ('publication_status', models.CharField(choices=[('WITH_PUBLICATION', 'With Publication'), ('WITHOUT_PUBLICATION', 'Without Publication')], max_length=30)),
                ('student_names', models.TextField(blank=True, help_text='Names of students guided', null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, storage=core.storage.Student_project_Storage(), upload_to='')),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_project_works', to='accounts.user')),
            ],
        ),
    ]
